Repository JoberChipFrappuccino/joberchip-be-demo, pull requests merged in 2023-10, with the labels that each got.

#76 깃헙 액션 스크립트 오류 수정
  .github/workflows/deploy.yml
Labels: enhancement

#78 [Hotfix] 이미지블록 수정기능 에러
  api/server-v1/src/main/java/kr/joberchip/server/v1/block/controller/ImageBlockController.java
Labels: fix

#81 [api-server-v1] fix: 페이지 상세 조회시 맵블록 정보 빠져있던 부분 추가
  api/server-v1/src/main/java/kr/joberchip/server/v1/page/controller/dto/SharePageDetailResponseDTO.java
  api/server-v1/src/main/java/kr/joberchip/server/v1/page/service/SharePageService.java
Labels: fix

#83 [api-server-v1] fix: 텍스트 블록 생성 오류 수정
  api/server-v1/src/main/java/kr/joberchip/server/v1/block/controller/TextBlockController.java
  api/server-v1/src/main/java/kr/joberchip/server/v1/block/controller/dto/TextBlockDTO.java
  api/server-v1/src/main/java/kr/joberchip/server/v1/block/service/TextBlockService.java
  libs/core/src/main/java/kr/joberchip/core/block/TextBlock.java
Labels: fix

#84 [api-server-v1] fix: 페이지 위치 이동 부분 오류 수정
  api/server-v1/src/main/java/kr/joberchip/server/v1/page/controller/SharePageController.java
  api/server-v1/src/main/java/kr/joberchip/server/v1/page/service/SharePageService.java
Labels: fix

#87 [api-server-v1] fix: 텍스트 블록 수정 오류 수정
  api/server-v1/src/main/java/kr/joberchip/server/v1/block/controller/TextBlockController.java
Labels: fix

#88 [api-server-v1] fix: 텍스트 블록 수정 오타 수정
  api/server-v1/src/main/java/kr/joberchip/server/v1/block/service/TextBlockService.java
Labels: fix

#90 [api-server-v1] fix: @RequestBody 정리, @Transactional 어노테이션 추가
  api/server-v1/src/main/java/kr/joberchip/server/v1/block/controller/VideoBlockController.java
  api/server-v1/src/main/java/kr/joberchip/server/v1/block/service/VideoBlockService.java
Labels: fix

#92 [api-server-v1] fix: 페이지 상세 조회시 페이지 프로필 이미지 링크도 함께 전달하도록 수정
  api/server-v1/src/main/java/kr/joberchip/server/v1/page/controller/dto/SharePageDetailResponseDTO.java
Labels: enhancement

#96 [api-server-v1] update: TextBlockService - block entity 조회 실패하는 경우 ApiClientException 날리도록 수정
  api/server-v1/src/main/java/kr/joberchip/server/v1/block/service/TextBlockService.java
Labels: fix

#98 [api-server-v1] update: TextBlockDTO - @Lob 어노테이션 추가
  api/server-v1/src/main/java/kr/joberchip/server/v1/block/controller/dto/TextBlockDTO.java
Labels: fix

#104 [api-server-v1] feat: 하위 페이지 생성시 블록처럼 보이도록 응답 객체 반환
  api/server-v1/src/main/java/kr/joberchip/server/v1/page/controller/SharePageController.java
Labels: enhancement

#105 [api-server-v1] feat: 페이지 상세보기 응답에 visible 포함하도록 변경 (프론트 요청)
  api/server-v1/src/main/java/kr/joberchip/server/v1/page/controller/dto/SharePageDetailResponseDTO.java
Labels: enhancement

#107 [api-server-v1] fix: 페이지 프로필 이미지 교체시 기존 디폴트 이미지 삭제
  api/server-v1/src/main/java/kr/joberchip/server/v1/page/service/SharePageService.java
Labels: fix

#108 [api-server-v1] fix: @Lob 어노테이션 추가 - 비디오 링크 첨부 관련 오류
  api/server-v1/src/main/java/kr/joberchip/server/v1/block/controller/dto/BlockResponseDTO.java
  api/server-v1/src/main/java/kr/joberchip/server/v1/block/controller/dto/VideoBlockDTO.java
Labels: fix

#110 [root] update - CD 관련 default branch 변경 (develop -> release)
  .github/workflows/deploy.yml
Labels: refactor

#113 [api-server-v1] feat: UserProfile 조회 API 추가 - /v1/user/profile (#112)
  api/server-v1/src/main/java/kr/joberchip/server/v1/_config/ServerSecurityConfig.java
  api/server-v1/src/main/java/kr/joberchip/server/v1/user/controller/UserController.java
  api/server-v1/src/main/java/kr/joberchip/server/v1/user/controller/dto/UserProfileDTO.java
  api/server-v1/src/main/java/kr/joberchip/server/v1/user/service/UserService.java
Labels: enhancement
